name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: DEV2B/core-cicd-templates/.github/workflows/docker-build.yml@main
    with:
      app_name: dev2b-landing
      context: "app"
      dockerfile_path: "Dockerfile"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
