name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  docker:
    uses: dev2b-tec/core-cicd-templates/.github/workflows/ci-docker.yml@main
    permissions:
      contents: read
      packages: write
    with:
      image-name: ghcr.io/${{ github.repository }}
      registry: ghcr.io
      dockerfile: Dockerfile
      context: app
      push: ${{ github.event_name == 'push' }}
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
